openapi: 3.0.0
servers:
  - url: http://localhost:8080
    description: Local server
info:
  title: Node.js CQRS App
  version: 1.0.0

paths:
  /v1/products:
    get:
      tags:
        - Products
      summary: Products list
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          required: true
          description: Offset for pagination
        - in: query
          name: limit
          schema:
            type: integer
          required: true
          description: Limit for pagination
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidQueryParametersError'
              examples:
                Bad Request:
                  $ref: '#/components/examples/InvalidQueryParametersError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/InternalServerError'
    post:
      tags:
        - Products
      summary: Create product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Product 1
                description:
                  type: string
                  example: Cool product
                price:
                  type: integer
                  example: 5050
                  description: Price in cents
                stock:
                  type: integer
                  example: 10
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                    example: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidBodyError'
              examples:
                Bad Request:
                  $ref: '#/components/examples/InvalidBodyError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/InternalServerError'
  /v1/products/{productId}/restock:
    post:
      tags:
        - Products
      summary: Restock product
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: Product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 10
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  newStock:
                    type: integer
                    example: 20
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidBodyError'
              examples:
                Bad Request:
                  $ref: '#/components/examples/InvalidBodyError'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductNotFoundError'
              examples:
                Product Not Found:
                  $ref: '#/components/examples/ProductNotFoundError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/InternalServerError'
  /v1/products/{productId}/sell:
    post:
      tags:
        - Products
      summary: Sell product
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: Product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  newStock:
                    type: integer
                    example: 19
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/InvalidBodyError'
                  - $ref: '#/components/schemas/NotEnoughStockError'
              examples:
                Bad Request:
                  $ref: '#/components/examples/InvalidBodyError'
                Not Enough Stock:
                  $ref: '#/components/examples/NotEnoughStockError'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductNotFoundError'
              examples:
                Product Not Found:
                  $ref: '#/components/examples/ProductNotFoundError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/InternalServerError'
  /v1/orders:
    get:
      tags:
        - Orders
      summary: Orders list
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          required: true
          description: Offset for pagination
        - in: query
          name: limit
          schema:
            type: integer
          required: true
          description: Limit for pagination
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidQueryParametersError'
              examples:
                Bad Request:
                  $ref: '#/components/examples/InvalidQueryParametersError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/InternalServerError'
    post:
      tags:
        - Orders
      summary: Create order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  example: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
                products:
                  type: object
                  description: Quantity of each product
                  example: { '4ddbfc6c-f5f2-456d-9420-ca6eba1dc887': 1 }
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    example: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidBodyError'
              examples:
                Bad Request:
                  $ref: '#/components/examples/InvalidBodyError'
                Not enough stock:
                  $ref: '#/components/examples/NotEnoughStockWithIdError'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductNotFoundWithIdError'
              examples:
                Product Not Found:
                  $ref: '#/components/examples/ProductNotFoundWithIdError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/InternalServerError'

components:
  schemas:
    InvalidBodyError:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: object
    InvalidQueryParametersError:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: object
    InternalServerError:
      type: object
      properties:
        error:
          type: string
    ProductNotFoundError:
      type: object
      properties:
        error:
          type: string
    ProductNotFoundWithIdError:
      type: object
      properties:
        error:
          type: string
        details:
          type: object
          properties:
            productId:
              type: string
    NotEnoughStockError:
      type: object
      properties:
        error:
          type: string
        details:
          type: object
          properties:
            wanted:
              type: integer
            available:
              type: integer
    NotEnoughStockWithIdError:
      type: object
      properties:
        error:
          type: string
        details:
          type: object
          properties:
            productId:
              type: string
            wanted:
              type: integer
            available:
              type: integer
    Product:
      type: object
      properties:
        _id:
          type: string
          example: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
        name:
          type: string
          example: Product 1
        description:
          type: string
          example: Cool product
        price:
          type: integer
          example: 5050
          description: Price in cents
        stock:
          type: integer
          example: 10
    Order:
      type: object
      properties:
        _id:
          type: string
          example: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
        customerId:
          type: string
          example: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
        products:
          type: object
          description: Quantity of each product
          example: { '4ddbfc6c-f5f2-456d-9420-ca6eba1dc887': 1 }
  examples:
    InvalidBodyError:
      value:
        error: Invalid request body
    InvalidQueryParametersError:
      value:
        error: Invalid request query parameters
    InternalServerError:
      value:
        error: Internal server error
    ProductNotFoundError:
      value:
        error: Product not found
    ProductNotFoundWithIdError:
      value:
        error: Product not found
        details:
          productId: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
    NotEnoughStockError:
      value:
        error: Not enough stock
        details:
          wanted: 50
          available: 20
    NotEnoughStockWithIdError:
      value:
        error: Not enough stock
        details:
          productId: 4ddbfc6c-f5f2-456d-9420-ca6eba1dc887
          wanted: 50
          available: 20
